import fs from 'fs';
import path from 'path';

const paths = [
  // Paper 1
  "paper-1/chapter-01/nature-evolution",
  "paper-1/chapter-01/scope-excitement",
  "paper-1/chapter-01/concepts-laws-theories",
  "paper-1/chapter-01/interdisciplinary-connections",
  "paper-1/chapter-01/space-time-mass",
  "paper-1/chapter-01/units-dimensions",
  "paper-1/chapter-01/measurement-principles-history",
  "paper-1/chapter-01/errors-in-measurement",
  "paper-1/chapter-01/precision-significant-figures",
  "paper-1/chapter-01/practical",
  "paper-1/chapter-02/vector-properties",
  "paper-1/chapter-02/vector-representation",
  "paper-1/chapter-02/special-vectors",
  "paper-1/chapter-02/parallelogram-law",
  "paper-1/chapter-02/vector-resolution",
  "paper-1/chapter-02/3d-rectangular-system",
  "paper-1/chapter-02/dot-cross-products",
  "paper-1/chapter-02/calculus-foundations",
  "paper-1/chapter-02/vector-calculus",
  "paper-1/chapter-02/vector-operators",
  "paper-1/chapter-03/reference-frames",
  "paper-1/chapter-03/calculus-kinematics",
  "paper-1/chapter-03/motion-graphs",
  "paper-1/chapter-03/projectile-motion",
  "paper-1/chapter-03/falling-bodies",
  "paper-1/chapter-03/uniform-circular-motion",
  "paper-1/chapter-04/intuitive-force",
  "paper-1/chapter-04/newtons-second-law",
  "paper-1/chapter-04/newtons-laws-relations",
  "paper-1/chapter-04/applications-of-newton-laws",
  "paper-1/chapter-04/force-field-intensity",
  "paper-1/chapter-04/linear-momentum-rockets",
  "paper-1/chapter-04/moment-of-inertia",
  "paper-1/chapter-04/angular-kinematics",
  "paper-1/chapter-04/torque-rotational-energy",
  "paper-1/chapter-04/torque-inertia-relation",
  "paper-1/chapter-04/conservation-angular-momentum",
  "paper-1/chapter-04/centripetal-force-banking",
  "paper-1/chapter-04/collisions",
  "paper-1/chapter-04/practical",
  "paper-1/chapter-05/work-energy-basics",
  "paper-1/chapter-05/spring-variable-work",
  "paper-1/chapter-05/work-energy-theorem",
  "paper-1/chapter-05/power-pumps-efficiency",
  "paper-1/chapter-06/keplers-laws",
  "paper-1/chapter-06/variation-of-g",
  "paper-1/chapter-06/potential-field-escape",
  "paper-1/chapter-06/satellites",
  "paper-1/chapter-07/elasticity-stress-strain",
  "paper-1/chapter-07/elastic-moduli",
  "paper-1/chapter-07/viscosity-stokes-law",
  "paper-1/chapter-07/surface-tension-capillarity",
  "paper-1/chapter-08/periodic-shm-intro",
  "paper-1/chapter-08/differential-equation-shm",
  "paper-1/chapter-08/shm-energy-equations",
  "paper-1/chapter-08/simple-pendulum",
  "paper-1/chapter-08/spring-mass-system",
  "paper-1/chapter-09/progressive-wave-equation",
  "paper-1/chapter-09/standing-waves",
  "paper-1/chapter-09/beats-sound-intensity",
  "paper-1/chapter-09/doppler-effect",
  "paper-1/chapter-10/gas-laws-ideal-gas",
  "paper-1/chapter-10/kinetic-theory-rms",
  "paper-1/chapter-10/degrees-of-freedom-equipartition",
  "paper-1/chapter-10/humidity-dew-point",
  // Paper 2
  "paper-2/chapter-01/zeroth-law-thermometry",
  "paper-2/chapter-01/first-law-internal-energy",
  "paper-2/chapter-01/thermodynamic-processes",
  "paper-2/chapter-01/second-law-statements",
  "paper-2/chapter-01/reversible-irreversible",
  "paper-2/chapter-01/carno-cycle-refrigerator",
  "paper-2/chapter-01/entropy-disorder",
  "paper-2/chapter-02/coulombs-law-field",
  "paper-2/chapter-02/intensity-potential",
  "paper-2/chapter-02/equipotential-surface",
  "paper-2/chapter-02/electric-dipole",
  "paper-2/chapter-02/charge-quantization",
  "paper-2/chapter-02/dielectrics-polarization",
  "paper-2/chapter-02/capacitors-energy",
  "paper-2/chapter-02/gauss-law-derivation",
  "paper-2/chapter-02/coulombs-law-limitations",
  "paper-2/chapter-03/resistance-temperature-coefficient",
  "paper-2/chapter-03/joules-heating-effect",
  "paper-2/chapter-03/cells-internal-resistance",
  "paper-2/chapter-03/kirchhoffs-laws-circuits",
  "paper-2/chapter-03/wheatstone-bridge",
  "paper-2/chapter-03/shunt-range-extension",
  "paper-2/chapter-03/practical",
  "paper-2/chapter-04/oersted-experiment",
  "paper-2/chapter-04/biot-savart-ampere",
  "paper-2/chapter-04/lorentz-force",
  "paper-2/chapter-04/hall-effect",
  "paper-2/chapter-04/torque-magnetic-loop",
  "paper-2/chapter-04/electron-spin-moment",
  "paper-2/chapter-04/geomagnetism-elements",
  "paper-2/chapter-04/magnetic-materials-domains",
  "paper-2/chapter-04/hysteresis-electromagnets",
  "paper-2/chapter-05/electromagnetic-induction-faraday",
  "paper-2/chapter-05/lenzs-law-conservation",
  "paper-2/chapter-05/self-mutual-inductance",
  "paper-2/chapter-05/ac-generator",
  "paper-2/chapter-05/ac-rms-peak-values",
  "paper-2/chapter-05/transformers-power-loss",
  "paper-2/chapter-06/fermats-principle",
  "paper-2/chapter-06/lens-makers-formula",
  "paper-2/chapter-06/prism-minimum-deviation",
  "paper-2/chapter-06/microscopes-telescopes",
  "paper-2/chapter-06/practical",
  "paper-2/chapter-07/em-spectrum",
  "paper-2/chapter-07/huygens-principle",
  "paper-2/chapter-07/interference-youngs-experiment",
  "paper-2/chapter-07/diffraction-grating",
  "paper-2/chapter-07/polarization-brewster-malus",
  "paper-2/chapter-08/special-relativity-postulates",
  "paper-2/chapter-08/time-dilation-length-mass",
  "paper-2/chapter-08/mass-energy-equivalence",
  "paper-2/chapter-08/photoelectric-effect",
  "paper-2/chapter-08/xray-compton-debroglie",
  "paper-2/chapter-09/bohr-model-spectra",
  "paper-2/chapter-09/radioactivity-decay",
  "paper-2/chapter-09/nuclear-binding-fission-fusion",
  "paper-2/chapter-10/energy-bands-semiconductors",
  "paper-2/chapter-10/pn-junction-rectifiers",
  "paper-2/chapter-10/transistors-amplification",
  "paper-2/chapter-10/logic-gates",
  "paper-2/chapter-11/big-bang-universe",
  "paper-2/chapter-11/stellar-evolution-black-holes",
  "paper-2/chapter-11/hubbles-law-expansion"
];

for (const relPath of paths) {
  const filePath = path.join('src', 'content', 'docs', `${relPath}.md`);
  const dirPath = path.dirname(filePath);

  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  if (!fs.existsSync(filePath)) {
    const rawTitle = path.basename(relPath).replace(/-/g, ' ');
    const title = rawTitle.charAt(0).toUpperCase() + rawTitle.slice(1);
    const content = `---\ntitle: "${title}"\ndescription: "PhysicsVerse Pioneer Module"\n---\n\n## কনটেন্ট দ্রুত যুক্ত করা হবে।\n`;
    fs.writeFileSync(filePath, content, 'utf8');
  }
}

console.log(`Success! All ${paths.length} lesson files created.`);